[package]
name = "dsos"
version = "0.1.0"
edition = "2024"

[build]
target = "x86_64-llvm-target.json"

[dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[[bin]]
name = "dsos"
test = false
bench = false
