[package]
name = "dsos"
version = "0.1.0"
edition = "2024"

[dependencies]
bootloader = "0.9"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[[bin]]
name = "dsos"
test = false
bench = false
